# Generated by Django 5.1.4 on 2025-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='testimonial',
            field=models.TextField(max_length=700),
        ),
    ]
