# Generated by Django 5.1.4 on 2025-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projetct_name', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('project_Img', models.ImageField(upload_to='project/')),
            ],
        ),
    ]
